---
#
# Common foreman config. Override in group_vars/<location>.yaml when needed)
#

# ansible defaults
ansible_ssh_user: iaas

# default mgmt gw is proxy-02
foreman_subnet_gateway: "{{  mgmt_network_cidr | ansible.utils.ipaddr('97') | ansible.utils.ipaddr('address') }}"

# default repo env
repo_env: 'prod'

# latest os versions
el8_latest: "AlmaLinux 8.10"
el9_latest: "AlmaLinux 9.5"

# default compute resource
foreman_compute_resources:
  - name: "{{ location }}-controller-01.{{ domain_mgmt }}"

# puppet environments
foreman_puppet_environments:
  - name: "production"
  - name: "admin"
  - name: "xena"
  - name: "yoga"
  - name: "zed"

# Dynamic vars
mgmt_network_cidr: "{{ ansible_facts[mgmt_interface]['ipv4']['network']}}/{{ansible_facts[mgmt_interface]['ipv4']['prefix'] }}"

# Foreman global settings
foreman_server_url: "https://foreman.{{ domain_mgmt }}"
foreman_username: 'admin'
foreman_password: 'changeme'
foreman_validate_certs: false

# NREC vars
foreman_template_prefix: 'norcams-'
foreman_repo_server: "https://download.iaas.uio.no/nrec/{{ repo_env }}"

# Autoload all templates in role (both provisioning and snippets)
foreman_autoload_templates: true

foreman_deploy_default_pxelinux_cfg: true

# misc
ca_backup_dir: '/opt/repo/secrets/dumps/'
