---
- name: Write foreman host paramaters to file
  hosts: "admin"
  vars:
    host_filter: "{{ location }}"
    foreman_auth: &foreman_auth
      username: "{{ foreman_username }}"
      password: "{{ foreman_password }}"
      server_url: "{{ foreman_server_url }}"
      validate_certs: "{{ foreman_validate_certs | default('true') }}"

  tasks:

  - name: "Read all Registries"
    theforeman.foreman.resource_info:
      <<: *foreman_auth
      resource: hosts
      full_details: true
    register: result

  - name: Create dumps directory
    ansible.builtin.file:
      state: directory
      path: "{{ inventory_dir }}/dumps"
    delegate_to: localhost

  - name: Write all parameters for host to file
    ansible.builtin.copy:
      content: "{{ item.all_parameters | to_nice_yaml }}"
      dest: "{{ inventory_dir }}/dumps/{{ item.name.split('.')[0] }}.yaml"
    loop: "{{ result.resources }}"
    loop_control:
      label: "{{ inventory_dir }}/dumps/{{ item.name.split('.')[0] }}.yaml"
    delegate_to: localhost
    when: host_filter in item.name
